#!/bin/sh
# Dmenu search with history

datadir=/usr/local/share
handledir=$datadir/dsearch
search='https://duckduckgo.com?q='
config=${XDG_CONFIG_HOME:-~/.config}/dsearch

create_menu() {
	test -f "$config"/entriesrc && . "$config"/entriesrc
	# Bang completions
	cd -- "$handledir" || exit 1
	find . -type f -printf "!%f\n" | sort -u
	printf '%s\n%s\n%s\n%s\n' '!snap' '!stop' '!close' '!win'

}

get_selection() {
	if test -z "$1"; then
		create_menu | dmenu -p Search | sed 's/^.*http/http/'
	else
		printf "$1\n"
	fi
}

handle_results() { # args -> launch
	while read -r input; do
		if test -f "$input" 2>/dev/null; then
			plumber "$input" &
			exit 0
		fi
		# We test user's case first
		case $input in
			!lyrics) exec "$handledir"/lyrics ;;
			!pocket) exec "$handledir"/pocket ;;
			!photo)  exec "$handledir"/photo  ;;
			!mpvl)   exec "$handledir"/mpvl   ;;
			!read)   exec "$handledir"/read   ;;
			!docs)   exec "$handledir"/docs   ;;
			!game)   exec "$handledir"/game   ;;
			!save)   exec "$handledir"/save   ;;
			!link)   exec "$handledir"/link   ;;
			!song)   exec "$handledir"/song   ;;
			!math)   exec "$handledir"/math   ;;
			!pass)   exec "$handledir"/pass   ;;
			!rss)    exec "$handledir"/rss    ;;
			!man)    exec "$handledir"/man    ;;
			!pb)     exec "$handledir"/pb     ;;
			!np)     exec "$handledir"/np     ;;


			!pl\ save)        exec "$handledir"/youtube/savesearch ;;
			!reddit\ *)       exec "$handledir"/reddit "${input#*reddit }" ;;
			!lyrics\ *)       exec "$handledir"/lyrics "${input#*lyrics }" ;;
			!godoc\ *)	      exec "$handledir"/godoc  "${input#*godoc }"  ;;
			!album\ *)        exec "$handledir"/album  "${input#*album }"  ;;
			!quote\ *)        exec "$handledir"/quote  "${input#*quote }"  ;;
			!save\ *)         exec "$handledir"/save   "${input#*save }"   ;;
			!song\ *)         exec "$handledir"/song   "${input#*song }"   ;;
			!code\ *)         exec "$handledir"/code   "${input#*code }"   ;;
			!dict\ *)         exec "$handledir"/dict   "${input#*dict }"   ;;
			!math\ *)         exec "$handledir"/math   "${input#*math }"   ;;
			!man\ *)          exec "$handledir"/man    "${input#*man }"    ;;
			!pkg\ *)	  exec "$handledir"/pkg    "${input#*pkg }"    ;;
			!gh\ *)   	  exec "$handledir"/gh     "${input#*gh }"     ;;
			!pl\ *)           exec "$handledir"/yt     "$input"            ;;
			!ch\ *)		  exec "$handledir"/yt     "$input"           ;;
			!yt\ *)           exec "$handledir"/yt     "${input#*yt }"     ;;
 			!pb\ *)           exec "$handledir"/pb     "${input#*pb }"     ;;
			!rq\ *)           exec "$handledir"/rq     "${input#*rq }"     ;;
			!is\ *)     plumber `"$handledir"/is     "${input#*is }"`   ;;
			!w\ *)		  exec "$handledir"/w	   "${input#*w }" 	   ;;
			!g\ *)		  exec "$handledir"/g      "${input#*g }"      ;;
		esac
		test -f "$config"/handlersrc && . "$config"/handlersrc "$input"
		case $input in
			!close) pkill surf; pkill chromium ;;
			# Not really search related, but useful
			!snap)   exec "$handledir"/rec 'snap'                    ;;
			!stop)   exec "$handledir"/rec 'stop'                    ;;
			!win)    exec "$handledir"/rec 'win'		     ;;
			!rec)    exec "$handledir"/rec 'vid'                     ;;
			!*)      exec browse "$search${input%% *}+${input#* }"   ;;
			*)       exec browse "$input" ;;
		esac
	done
}

# Main
get_selection "$1" | handle_results
