#!/bin/sh

# Code search using dmenu, ag (single string)
handle() {
	while read -r result; do
		subres="${result#*:}"
		edit +"${subres%%:*}" "$HOME/${result%%:*}" &
	done
}

ag "$1" "$HOME" | dmenu -p "Select file: " | handle
