#!/usr/bin/env bash
# Bash lets me do lazy substitutions
tmp="$(mktemp -d)"

fetch_data() {
    data=$(curl -sBX GET -L "$1" -A "Mozilla/5.0 (Linux; Android 6.0.1; Nexus  MOB3OD)" -o "$tmp"/data)
}

chunk() {
	while {
		read -r title
		read -r link
	} do 
		printf '%s - %s\n' "$title" "$link"
	done
}

parse() {
    jshon -QF "$tmp"/data -e items -a -e title -upe link -u
}

read -r KEY < "$XDG_DATA_HOME"/youtube/key
read -r ID < "$XDG_DATA_HOME"/youtube/gid

url="https://www.googleapis.com/customsearch/v1?key=$KEY&cx=$ID&q=${1// /+}&alt=json"

fetch_data "$url"
parse | chunk | dmenu -p "Results: " | awk '{ print $NF }' | plumber
rm -rf "$tmp"
