#!/bin/sh
## Small googler wrapper to get results

parse() {
	jshon -CQ -a -e title -upe url -u
}

chunk() {
	while {
		read -r title
		read -r url
	} do
		printf '%s - %s\n' "$title" "$url"
	done
}

handle() {
	while read -r line; do
		plumber "${line##*\ -\ }"
	done
}

PYTHONIOENCODING=utf-8 googler --json "$@" | parse | chunk | dmenu -p results | handle 
