#!/bin/sh
tmp=`mktemp`
conv_whitespace() {
	printf '%s\n' "$@" | sed 's/ /+/g'
}
while read -r title; do
	
	curl -s  "https://makeitpersonal.co/lyrics?artist=$(conv_whitespace "${title%% - *}")&title=$(conv_whitespace "${title##* - }")" > "$tmp"
done < "$XDG_RUNTIME_DIR"/statusbar/media

# Fire off results
"$TERMINAL" -c lyrics -e less "$tmp"
rm -rf "$tmp"
