#!/bin/sh
# Screen record or screen shot

PB="https://ptpb.pw/?u=1"

picture() {
	maim -d 1 --format=png /dev/stdout | curl -F c=@- "$PB" | sed 's/$/.png/' | xcmenu -ic
}

win() {
	WID=$(lsw | tail -n 1)
	maim --window="$WID" -d 1 --format=png /dev/stdout | curl -F c=@- "$PB" | sed 's/$/.png/' | xcmenu -ic
}

video() {
	ffmpeg -thread_queue_size 128 -f alsa -ac 1 -i hw:2,0 -f
x11grab -r 30 -s 1366x768 -i :0.0 -acodec pcm_s16le -vcodec
libx264 -preset ultrafast -threads 0 -y - | curl -F c=@- "$PB" | xcmenu -ic
 	#ffmpeg -y -video_size "$(wattr w "$(lsw -r)")x$(wattr h "$(lsw -r)")" -framerate 60 -f x11grab -i "$DISPLAY" -f matroska - | curl -F c=@- "$PB" | sed 's/$/.mkv/' | xcmenu -ic 
}

## Main
case "$1" in
 	snap) picture ;;
 	win)  win ;;
	vid)  video ;; 
	stop) pkill -SIGINT ffmpeg ;;
esac
