#!/usr/bin/env bash
## List current playlist
#  I generally have all of my music on the playlist
#  Adjust for your own needs


load() {
	local i=0
	current="$(mpc current)"
	mpc playlist | while read -r title; do
		if [[ $current == $title ]]; then
			printf '%s Now Playing: %s\n' "$((++i))" "$title"
		else
			printf '%s %s\n' "$((++i))" "$title"
		fi
	done | dmenu -p "Select song: "
}
## Main

if [[ $1 ]]; then
	result=$1
else
	result="$(load)"
fi

[[ $result ]] || exit 0

# If we don't have the song at all, grab it from youtube
if ! mpc playlist | grep "${result#*\ }"; then
	youtube-dl "ytsearch:$result" --get-url --audio-format mp3 -f 140 | mpc insert
	mpc next
else
	mpc play "${result%%\ *}"
	sleep 2
	# Should hopefully only hit mpg123 and ogg123. This is considered bad programming though, as it can break in weird ways. This whole script is just bad - but it'll get fixed when there's more time
	if ! pgrep 123; then
		stream
	fi
fi
