#!/bin/sh
# Create menu based on URLs and titles.

load() {
	grep 'Title.*=' "$XDG_DATA_HOME/mpv/$1" | sed 's/Title[0-9]\{1,\}=//'
}

scrub() {
	while read -r name; do
    	awk -v result="$name" 's=index($0,result) { print int((NR-1)/2) }' "$XDG_DATA_HOME/mpv/$1"
	done
}

handle() {
	while read -r pos; do
		grep File"$pos"= "$XDG_DATA_HOME/mpv/$1" | sed 's/File[0-9]\{1,\}=//' 
	done
}
# Main
load "$1" | dmenu -p "Select video:" | scrub "$1" | handle "$1" | plumber
